#!/usr/bin/env bash
#
# Script to set colors generated by 'wal'
# https://github.com/dylanaraps/wal
# Source generated colors.
. "${HOME}/.cache/wal/colors.sh"

reload_dunst() {
    pkill dunst
    dunst \
	      -frame_width 2 \
        -lfr "${color3}" \
        -nfr "${color3}" \
        -cfr "${color3}" \
        -lb "${color0}" \
        -nb "${color0}" \
        -cb "${color0}" \
        -lf "${color2}" \
        -bf "${color2}" \
        -cf "${color2}" \
        -nf "${color7}" &
}

reload_dunst
